baseUrl: https://jay.jvf.cc/
languageCode: en-us
theme: terminal
pagination:
  pagerSize: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: green
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 5
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: true
  # center theme with default width
  centerTheme: false
  sectionPagesMenu: posts

languages:
  en:
    params:
      languageName: English
      title: Thoughts from Jay
      subtitle: Jay Faulkner's Personal Blog
      keywords: ''
      menuMore: Show more
      readMore: Read more
      readOtherPosts: Read other posts

      logo:
        logoText: jay.jvf.cc
        logoHomeLink: /

menu:
  main:
  - identifier: publications
    name: Publications/Talks
    url: /publications
    weight: 97
  - identifier: about
    name: About Jay
    url: /about
    weight: 98
  - identifier: socials
    name: Find me at...
  - identifier: mastodon
    name: https://oldos.me/@Jay
    url: https://oldos.me/@Jay
    parent: socials
    weight: 1
  - identifier: youtube
    name: YouTube.com/jayofdoom
    url: https://www.youtube.com/jayofdoom
    parent: socials
    weight: 2
  - identifier: Linkedin
    name: LinkedIn.com/in/jayfaulkner
    url: https://www.linkedin.com/in/jayfaulkner
    parent: socials
    weight: 3
  - identifier: email
    name: 'jay at jvf dot cc (email)'
    url: mailto:jay-at-jvf-cc
    parent: socials
    weight: 99

deployment:
  order: [".jpg$", ".gif$"]

  targets:
    name: "google jay.jvf.cc"
    URL: "gs://jay.jvf.cc"
  
  matchers:
    - pattern: "^.+\\.(js|css|svg|ttf)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: "^.+\\.(png|jpg)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: false
    - pattern: "^sitemap\\.xml$"
      contentType: "application/xml"
      gzip: true
    - pattern: "^.+\\.(html|xml|json)$"
      gzip: true


